THISPKG	= array
SEARCH	=
EXTRA_H_FLAGS   =
EXTRA_HBC_FLAGS =

DIRS	= \
	Data Data/Array

SRCS	= \
	Data/Array.hs

# Here are the main rules.
include ../Makefile.common

# some extra rules

# Here are any extra dependencies.

# C-files dependencies.

